micronaut:
  application:
    name: sandbox
  security:
    intercept-url-map:
      - pattern: /api/tic-tac-toe/**
        access:
          - isAuthenticated()
      - pattern: /**
        access:
          - isAnonymous()
    basic-auth:
      enabled: true
  router:
    static-resources:
      site:
        paths:
          - classpath:public
